<a href="https://colab.research.google.com/github/sandeepkhcltech/aiml/blob/main/multivariate_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# python implementation - multivariate linear regression model that can predict the product sales based on the advertising budget allocated to different channels. The features are TV Budget ($),Radio Budget ($),Newspaper Budget ($) and the output is Sales (units)

# step 1: import the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from google.colab import drive


# step 2: reading the data and splitting it to input and output


In [9]:

# Step 1: Mount Google Drive
#drive.mount('/content/drive')
dataset = pd.read_csv('https://raw.githubusercontent.com/sandeepkhcltech/aiml/refs/heads/main/marketing_budget_sales.csv')
#dataset = pd.read_csv('/content/drive/My Drive/marketing_budget_sales.csv')
inputx = dataset.iloc[:, :-1].values
outputy = dataset.iloc[:, 1].values

In [3]:
print(dataset)

   TV Budget ($)  Radio Budget ($)  Newspaper Budget ($)  Sales (units)
0          230.1              37.8                  69.2           22.1
1           44.5              39.3                  45.1           10.4
2           17.2              45.9                  69.3            9.3
3          151.5              41.3                  58.5           18.5
4          180.8              10.8                  58.4           12.9
5            8.7              48.9                  75.0            7.2
6           57.5              32.8                  23.5           11.8
7          120.2              19.6                  11.6           13.2
8          144.1              16.0                  40.3           15.6
9          111.6              12.6                  37.9           12.2


# step 3: select one thirds of the data for testing and two thirds for training

In [4]:
input_train, input_test, output_train, output_test = train_test_split(inputx, outputy, test_size = 1/4, random_state = 7)

# step 4: selecting the Linear Regression model (common for univariate or multivariate)


In [5]:
model = LinearRegression()
print("\nThe parameters of the model are\n\n",model.get_params())
#print(model.set_params())
print("\nThe model we are using is ", model.fit(input_train, output_train))


The parameters of the model are

 {'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

The model we are using is  LinearRegression()


# step 5: testing or model prediction using testinput

In [6]:

# Take user input
tv = float(input("\nEnter TV Budget ($): "))
radio = float(input("Enter Radio Budget ($): "))
newspaper = float(input("Enter Newspaper Budget ($): "))

testinput = [[tv, radio, newspaper]]
predicted_output = model.predict(testinput)

# Display results
print('\nThe input advertising budgets are:', testinput)
print('The predicted sales (units) are:', predicted_output[0])

yes = input("\nCan I proceed\n")



Enter TV Budget ($): 10
Enter Radio Budget ($): 20
Enter Newspaper Budget ($): 30

The input advertising budgets are: [[10.0, 20.0, 30.0]]
The predicted sales (units) are: 20.00000000000001

Can I proceed



# step 6: Printing the testing results

In [7]:
print("\nThe test input  is as follows \n")
print(input_test)
# model predicting the Test set results
predicted_output = model.predict(input_test)
print("\nThe output  for the test input is as follows \n")
print(predicted_output)


The test input  is as follows 

[[144.1  16.   40.3]
 [  8.7  48.9  75. ]
 [230.1  37.8  69.2]]

The output  for the test input is as follows 

[16.  48.9 37.8]
